<?php

class CMerchantDef extends CModDef {
	protected function desc() {
		return array(
			self::MOD => array(
				self::G_NM=>'merchant',
				self::M_CS=>'utf-8',
				self::G_TL=>'商家系统',
				self::G_DC=>''
			),
			self::TBDEF => array(
				'merchant_info' => '(
					id int unsigned not null auto_increment,
					owner_id int unsigned not null,
					title varchar(32) not null,
					abstract varchar(128),
					phone varchar(16) not null,
					telephone varchar(16) not null,
					address varchar(32) not null,
					status tinyint,
					primary key(id),
					key(owner_id)
				)',
				'merchant_attachment' => '(
					id int unsigned not null auto_increment,
					merchant_id int unsigned not null,
					format tiny int not null, -- image, video, ...
					name varchar(16) not null,
					path varchar(128) not null, -- only path, not include domain
					abstract varchar(32) not null,
					primary key(id),
					key(merchant_id)
				)',
				/* merchant_product_***: auto generated by CMctProductControl */
				'merchant_product_attachment' => '(
					id int unsigned not null auto_increment,
					mp_id int unsigned not null,
					format tiny int not null, -- image, video, ...
					name varchar(16) not null,
					path varchar(128) not null, -- only path, not include domain
					abstract varchar(32) not null,
					primary key(id),
					key(mp_id)
				)',
			),
			self::PAGES => array(
			),
		);
	}
}

?>