<?php
$lang_zh_CN=array(
    'oper_succ'     => '操作成功&nbsp;!&nbsp;&nbsp;您可以继续编辑或者浏览',
    'close'         => '关闭',
    'login'         => '登录',
    'phone'         => '手机号码',
    'password'      => '密码',
    'captcha'       => '验证码',
    'reload_on_unclear' => '换一个',
    'invalid_phone' => '手机号码无效',
    'invalid_password'  => '密码无效',
    'invalid_captcha'   => '验证码无效',
    'remember_me'       => '记住我',
    'had_login'         => '您已登录！',
    'login_succeed'     => '登录成功！',
    'logout_succeed'    => '退出成功！',
    'login_first'       => '请先登录',
    
    'record_info'       => '录入信息',
    'edit_info'         => '编辑信息',
    'name'              => '姓名',
    'organization'      => '单位',
    'email'             => '邮箱',
    'select'            => '选择',
    'delete'            => '删除',
    
    'list'              => '列表',
    'search'            => '查询',
    'add'               => '添加',
    'edit'              => '编辑',
    'user'              => '用户',

    'data'              => '资料',
    'pwd_diff_or_error' => '密码不同或有误',
    'src_pwd_equal_new' => '原密码和新密码不能相同',
    'total_member'      => '共%d人',
    'member'            => '成员',
    'num'               => '数',
    'auto_login_in_next'=> '下次自动登录',
    'welcome'           => '欢迎登录快讯服务平台',
    'user_must_modify_pwd' => '用户须在首次登陆的时候修改密码',
    'invalid_device'    => '无效设备',
    'phone_exists'      => '手机号码已存在',
    'phone_not_exists'  => '手机号码不存在',
);
?>